@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}', feature: 'feature/.*'),
        platforms: [ 'ol8'],
        publishImage: true,
        yumOL8Repos: ['ol8_appstream'],
        yumOL9Repos: ['ol9_appstream'],
        architectures: ['x86_64', 'aarch64'],
)

